language: node_js
sudo: required
services:
  - docker
os:
  - linux
  - osx
osx_image: xcode9.3
env:
  - CANVAS_PREBUILT_VERSION="2.6.1-patched" CANVAS_VERSION_TO_BUILD="2.6.1" NODEJS_VERSIONS="6 7 8 9 10 11 12 13"
script:
  - >-
    if [ $TRAVIS_OS_NAME = "linux" ]; then
      make build-environment
      make build-canvas
    else
      bash ci/install.sh osx "$CANVAS_PREBUILT_VERSION" "$CANVAS_VERSION_TO_BUILD" "$NODEJS_VERSIONS";
    fi
